
typedef enum STATUS_GAS_BOILER {

    STATUS_APP_ERROR = -1, 
    STATUS_APP_AUTO, 
    STATUS_APP_MANUAL, 
    STATUS_APP_STARTING, 
    STATUS_APP_CONNECTING, 
    STATUS_APP_UPGRADING, 
    STATUS_APP_UNKNOWN


}STATUS_GAS_BOILER;



#define DEFAULT_TEMPERATURE_CORRECTION -3.5


void rainmaker_interface_init_environment();