

#define ESP_RMAKER_NAME_DEVICE "Gas Boiler"
#define ESP_RMAKER_NODE_NAME "ESP RainMaker Device"
#define ESP_RMAKER_MODEL_NAME "Rgb"
#define ESP_RMAKER_PARAM_SETPOINT_TEMPERATURE "esp.param.setpoint-temperature"
#define ESP_RMAKER_PARAM_SETPOINT_TEMPERATURE_NAME "Target temperature"
#define ESP_RMAKER_DEFAULT_SETPOINT_TEMPERATURE 21.5
#define ESP_RMAKER_PARAM_AC_MODE_NAME "mode"




#define TEXT_STATUS_APP_FACTORY "SIN CONFIGURAR"
#define TEXT_STATUS_APP_ERROR "ERROR"
#define TEXT_STATUS_APP_AUTO "AUTO"
#define TEXT_STATUS_APP_MANUAL "MANUAL"
#define TEXT_STATUS_APP_STARTING "INICIALIZANDO"
#define TEXT_STATUS_APP_CONNECTING  "CONECTANDO"
#define TEXT_STATUS_APP_SYNCING "SINCRONIZANDO"
#define TEXT_STATUS_APP_UPGRADING "ACTUALIZANDO"
#define TEXT_STATUS_APP_UNDEFINED "UNDEFINED"

void rainmaker_interface_init_environment();